# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            PicoLisp Libraries
tagline:          "AW's collection of PicoLisp libraries"
description:      ''
url:              https://picolisp.a1w.ca

author:
  name:           'Alexander Williams'
  url:            https://git.a1w.ca/aw

paginate:         1

# Custom vars
github:
  repo:           https://git.a1w.ca/aw/picolisp
